&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-align: center; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-weight: 600;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-size: 21px; font-family: 微软雅黑;&quot;&gt;服务万众&amp;nbsp; 不忘初心&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-align: center; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-weight: 600;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-size: 21px; font-family: 微软雅黑;&quot;&gt;36&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-weight: 600;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-size: 21px; font-family: 微软雅黑;&quot;&gt;氪简介&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-size: 19px; font-family: 微软雅黑;&quot;&gt;&amp;nbsp;&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;36&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;氪正式创办于2011年7月，专注科技创投领域，经过六年多发展，母公司（北京协力筑成信息服务股份有限公司，简称协力筑成）已成长为一家科技创新企业综合服务集团，拥有新商业传媒（36氪传媒）、联合办公空间（氪空间）、一级市场金融信息与系统提供商（鲸准）。协力筑成已是在规模、产业链覆盖及综合实力上领先的科技创新创业生态服务平台。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;2015&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;年10月，协力筑成作为全国双创周4家创业企业代表之一，受到了李克强总理接见。在最近三年里，国务院副总理刘延东、科技部部长万钢、中央政治局委员、北京市委书记郭金龙、河北省委书记赵克志、国家发改委副主任林念修、北京市副市长隋振江、国家统计局书记宁吉喆以及北京市委常委、常务副市长李士祥等各级领导，先后来协力筑成进行实地调研，对协力筑成在&amp;ldquo;双创&amp;rdquo;的大背景下，在创业服务上所做的探索，以及所取得的初步成绩，给予了充分认可。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;在过去六年多时间里，协力筑成服务了超过20,000多家创业企业，整个服务过程全部免费，尽最大可能帮助创业企业走出宝贵的第一步，整个市场上八成的优质创业项目，都可以在这里找到。同时，还建立了国内排名前15的顶级投资机构联盟，为这些优质创业者的成长提供融资支持。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;正是由于对这一愿景的认同，2015年，协力筑成还得到了国内最大的科技金融公司蚂蚁金融服务集团（以下简称蚂蚁金服）投资，以便更好地为中小微企业提供服务。除此之外，全球知名风投机构经纬中国、传统金融背景的国内领先的券商华泰证券等也都是协力筑成股东；2016年，引入了新股东招商局创投基金。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;从2016年开始，36氪逐步完成了架构拆分：形成了传媒、氪空间、创投三大子公司，其中36氪品牌由传媒业务使用；2017年8月，对创投业务进行了品牌升级，发布全新品牌&amp;ldquo;鲸准&amp;rdquo;，同36氪传媒、氪空间并列，母公司协力筑成致力于打造中国最大的科技创新企业综合服务集团。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;通过上述三大子公司业务，为中国无数创业者以及广大中小企业提供的全方位的系统服务，从资讯信息到帮助对接融资渠道、直接获得资金，到解决办公场地以及相关的配套孵化服务，希望成为带动中国创新创业的基础设施平台，为创业者乃至中小微企业，提供如水电煤一样无处不在的服务。&lt;/span&gt;&lt;/p&gt;

&lt;address style=&quot;box-sizing: border-box; margin: 1.6rem 0px; font-style: normal; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px;&quot;&gt;
&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-weight: 600;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-size: 19px; font-family: 微软雅黑;&quot;&gt;传媒业务-36氪传媒&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/address&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 35px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑; color: rgb(38, 38, 38);&quot;&gt;36&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑; color: rgb(38, 38, 38);&quot;&gt;氪传媒（北京品新传媒文化有限公司），中国领先的互联网资讯及服务提供商，新商业传媒。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑; color: rgb(38, 38, 38);&quot;&gt;36&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑; color: rgb(38, 38, 38);&quot;&gt;氪传媒成立于2011年7月，从科技博客开始，逐渐成长为中国创业投资领域领先新传媒和科技领先新传媒，聚拢了以创业者、投资人为核心的一批活跃读者。迄今为止，已让30,000多家初创公司在全球上亿受众面前曝光，其中有90%的初创项目是首次曝光，在国内早期被投项目中，有85%被36氪传媒报道覆盖，通过报道，有58%获机构投资，40%获得顶级机构投资，36氪传媒成为国内早期项目主要入口。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑; color: rgb(38, 38, 38);&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;2016&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑; color: rgb(38, 38, 38);&quot;&gt;年7月，前《第一财经周刊》联合创始人、著名投资人冯大刚加盟36氪传媒，同期，36氪拆分传媒业务独立运营，冯大刚出任36氪传媒总裁，除了继续夯实创业公司报道、扮演好新生代发现者的角色之外，36氪还从创投视角，加大对中后期创业公司乃至大公司的报道，从而逐步拓展到全商业领域，传递商业价值和趋势。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑; color: rgb(38, 38, 38);&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;围绕这一理念，&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; color: rgb(38, 38, 38); font-family: 微软雅黑; text-indent: 35px;&quot;&gt;36氪传媒的报道方向从&amp;ldquo;创投+科技&amp;rdquo;向&amp;ldquo;新商业&amp;rdquo;全面升级，致力于报道能代表未来经济趋势的新商业公司。新商业的特点是创新带来的高成长，比如出行的滴滴，吃饭的美团、饿了么，做智能手机的小米，信息阅读的今日头条，这些公司不仅快速改变了我们的生活，而且都是在几年内就成长为百亿美金估值的公司，而背后两大动力，一个是以移动互联网、人工智能为代表的&amp;ldquo;科技&amp;rdquo;，一个以创业融资为代表的&amp;ldquo;资本&amp;rdquo;，36氪传媒将以此作为切入点，来报道和深度服务这些能代表未来经济趋势的新商业公司。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 35px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; text-indent: 41px; font-family: 微软雅黑; color: rgb(38, 38, 38);&quot;&gt;2017&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; text-indent: 41px; font-family: 微软雅黑; color: rgb(38, 38, 38);&quot;&gt;年，36氪传媒的影响力、流量、市场活动影响力、销售收入等都获得显著提升，其中收入同比2016年增长了4倍，DAU同比增长了3倍，举办了MTA天漠音乐节、没想到游乐园、WISE大会等明星线下活动，并获得金字节&amp;ldquo;年度媒体奖&amp;rdquo;、美通社&amp;ldquo;最佳创新传媒奖&amp;rdquo;等奖项。公司也因为出色的管理文化和员工关怀获得智联招聘&amp;ldquo;2017年年度最佳雇主&amp;rdquo;殊荣。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; color: rgb(38, 38, 38); font-family: 微软雅黑; text-indent: 35px;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; 并且在过去的一年半间里，36氪传媒还在积极尝试新的业务模式和收入模式。包括尝试面向投资人的创投内容的直接收费，尝试面向普通用户的知识付费业务&amp;ldquo;开氪&amp;rdquo;，建立创业者服务团队进行城市和园区服务拓展，开拓音视频领域内容等。&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;/p&gt;

&lt;address style=&quot;box-sizing: border-box; margin: 1.6rem 0px; font-style: normal; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px;&quot;&gt;
&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-weight: 600;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-size: 19px; font-family: 微软雅黑;&quot;&gt;联合办公-氪空间&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/address&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;&lt;span style=&quot;box-sizing: border-box;&quot;&gt;不论项目好坏，在创业初期，创业者往往需要花费30%以上的时间与投资人进行沟通。据统计，如果在3个月间不能达成投资意向，创业者很有可能就此丧失创业机会。&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;为了解决这一难题，2014年4月，36氪成立自己的联合办公空间-氪空间（氪空间（北京）信息技术有限公司），也是最早一批中关村管委会认定的&amp;ldquo;创新型孵化器&amp;rdquo;，&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑; color: rgb(38, 38, 38);&quot;&gt;为全球的创业者提供高性价比的极致办公体验和全方位的深度创业服务，倡导共享的价值理念和开放的社群氛围，立志为创业者提供最好的产品和服务。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;氪空间是以联合办公为载体、以社群为纽带的中小企业服务平台。全国共拥有超过2,000家会员企业和20,000名会员，目前在全国9个城市拥有30个社区，分布在北京、上海、广州、杭州、南京、武汉、天津、成都、苏州。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;氪空间为企业提供办公空间，让智能化融入工作，提供高效贴心的服务，每一个人都可以在这里，灵活选择舒适的办公方式，结识伙伴，寻求机遇，发现未来。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;&amp;nbsp;2016&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;年1月，氪空间拆分独立运营，同年11月，氪空间宣布获得由普思资本和IDG资本的超过2亿元A+轮融资。2017年7月和9月，氪空间宣布获得中民投资本和IDG资本的数亿元A+轮系列融资。&lt;/span&gt;&lt;/p&gt;

&lt;address style=&quot;box-sizing: border-box; margin: 1.6rem 0px; font-style: normal; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px;&quot;&gt;
&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-weight: 600;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-size: 19px; font-family: 微软雅黑;&quot;&gt;创投业务-鲸准&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/address&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-size: 19px; font-family: 微软雅黑;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;鲸准（北京创业光荣信息科技有限责任公司）经过了7年的数据沉淀，通过精准的数据挖掘和智能机器学习以及专业化的数据运营。目前平台已经积累了60多万个项目信息，44万个投资机构信息以及18万个投资人信息。鲸准从2011年8月的36tree演变而来，目前已经从一个项目对接平台进化为一级市场领先的数据平台和系统提供商。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;在2017年8月15日，鲸准在品牌升级发布会上推出了针对投资人个人及投资机构的鲸准个人版及鲸准机构版两款产品。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;鲸准个人版收录国内一级市场的投融资数据。现已收录和维护一二级市场、TMT以及非TMT项目在内共60多万个项目，同时平台入驻7000+家投资机构及12000+活跃投资人。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;鲸准个人版产品亮点：&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;1&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;）项目：50万活跃项目数据库，算法+人工运维推送合适项目；&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;2&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;）信息：全面项目信息，包含联系方式、BP、运营数据、公开报道、舆情走势等；&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;3&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;）报告：实时收录一、二级市场数据，提供多维行业数据研报；&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;4&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;）行业：四级标签分类、智能交叉搜索，提供全面的行业图谱。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; 鲸准机构版是一款针对投资机构募投管退全流程的管理系统。系统依托在一级市场沉淀的50多万项目数据，实现对被投项目的精准搜索、精准管理、精准追踪。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;鲸准机构版产品亮点：&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;1&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;）投前：&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;一键沉淀标的项目，实时监测目标赛道；&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;投资流程自定义，随时随地智能协作。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;2&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;）投后：&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;实时项目信息流：实时异动提醒，舆情、热度、竞品尽在掌握；&lt;/span&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;智能投后管理：开设项目方接口，提供可视化运营、财务、回报数据分析。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;在数据的安全性上，鲸准接入了LOCKet以及知道创宇等数据安全合作伙伴，接入LOCKet后，企业内容产生时即经LOCKet加密，密钥由LOCKet管理，加密后的内容保存在服务商的服务器上。这样一来，服务商拿到的数据是加密数据，而LOCKet只保管密钥，只有拥有&amp;ldquo;数据＋密钥&amp;rdquo;的企业方才能解密数据。也就是说，36氪鲸准无法查看加密的数据，即使发生泄漏用户也不用慌，因为已经被安全保管。&lt;/span&gt;&lt;/p&gt;

&lt;p style=&quot;box-sizing: border-box; margin: 0px 0px 26px; word-wrap: break-word; color: rgb(61, 70, 77); font-family: &amp;quot;PingFang SC&amp;quot;, &amp;quot;Lantinghei SC&amp;quot;, &amp;quot;Helvetica Neue&amp;quot;, Helvetica, Arial, &amp;quot;Microsoft YaHei&amp;quot;, &amp;quot;\\5FAE软雅黑&amp;quot;, STHeitiSC-Light, simsun, &amp;quot;\\5B8B体&amp;quot;, &amp;quot;WenQuanYi Zen Hei&amp;quot;, &amp;quot;WenQuanYi Micro Hei&amp;quot;, sans-serif; font-size: 15px; text-indent: 31px; line-height: 23px;&quot;&gt;&lt;span style=&quot;box-sizing: border-box; font-family: 微软雅黑;&quot;&gt;鲸准核心团队由国内外大数据资深从业人士组成，总裁胡健以及核心团队具有在微软美国总部、微软亚洲研究院、雅虎北京研发中心、腾讯、金山云等企业一线搜索、数据研发及管理经验，其中不乏连续成功创业者及国际专利拥有者。&lt;/span&gt;&lt;/p&gt;
